### ISSUE TITLE
Only works with "vbs" language mode, but should work with the built-in "vb" mode

### ISSUE THREAD

**Issue by bplubell** [Luncher91/VBScript-vscode#11]
Does not find symbols in files associated with the built-in "vb" language mode.

Since VBScript and VBA have some slight differences, there are extensions that target one or the other. It would be nice to be able to configure in user settings which language modes or file extensions this processes.

At the least, add "vb", "vba", "vbscript" to [this line](https://github.com/Luncher91/VBScript-vscode/blob/53864b8d7d63c26dfde23169df54d0b458cd9240/client/src/extension.ts#L17) for the built-in, [VSCode VBA](https://marketplace.visualstudio.com/items?itemName=spences10.VBA), and [VBScript](https://marketplace.visualstudio.com/items?itemName=luggage66.VBScript) language modes.

**Comment by bplubell** [comment]
@Luncher91 I would like to contribute (test out the simpler solution), but I am having difficulty building and debugging the extension. It does not seem to follow current guidelines from the VSCode docs...

Could you give me some guidance on how to build and debug?

**Comment by Luncher91** [comment]
Hi,

Sorry for the late answer. I will have a look at your sugestion according the optional VBA support at the beginning of next year.

My extension is based on an older version of the language server example. You should be fine by following these steps:

1. Open server directory with code
2. Run Build Task
3. Open client directory with code
4. Go to the debug menu and "Launch Extension"

Make sure to uninstall the extension from the market before. Please feel free to ask if that does not work.

Best regards,
Andreas
