### ISSUE TITLE
ASP file support

### ISSUE THREAD

**Issue by Luncher91** [Luncher91/VBScript-vscode#13]
Commenter Scott Chapman on the Marketplace suggested ASP file support.

To fully support ASP files it is needed to detect the script parts of the ASP file.

**Comment by jonathanstar** [comment]
Is this in the works? This would be quite useful to me.

**Comment by Luncher91** [comment]
I am currently not working on it, but you are very welcome to contribute :-)

**Comment by Luncher91** [comment]
@kevinsproles Thank you very much for your pull request!
@jonathanstar Can you please check if version 1.1.0 fullfills your needs?

**Comment by jonathanstar** [comment]
Thanks @kevinsproles and @Luncher91, this is great and is going to be helpful for me!  One small thing I noticed is that symbols get out of wack when a sub/function doesn't have the end function keyword, and once they do it doesn't recalculate until the keypress after you type end function/end sub. check out the two screen shots below to see what I mean.

Before extra keypress the symbols in the outline are incorrect:

<img width="985" alt="before_keypress" src="https://user-images.githubusercontent.com/13529681/80239472-4b68d300-862e-11ea-8620-b7f21f0dd148.png">

After extra keypress (in this case I hit return) the symbols on the right sort themselves out correctly:

<img width="957" alt="after_keypress" src="https://user-images.githubusercontent.com/13529681/80239522-62a7c080-862e-11ea-9fe4-a325efc1694b.png">

The only other thing I'd say which would be awesome is if the symbols supported goto definition. Maybe I should make a separate feature request for that?

**Comment by Luncher91** [comment]
Oh, yes it would be great if you could create an issue for the first for incorrect parsing - that looks like a general issue not specific to ASP files.
And of yourse another one for your mentioned "goto" although I only know of the error handling routines containing "goto" - we can clarify that in the other thread.
