### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by fmeunierCC** [Luncher91/VBScript-vscode#15]
hello, 

newbie with VSCODE I don't know how to install your module...can you explain ? 

thanks

**Comment by Luncher91** [comment]
Hi,

Just start vscode, press Ctrl+P and paste "ext install andreaslenzen.vbscript-language-server-client"

That installs the extension from the MS marketplace. You can find this extension within the marketplace on the web https://marketplace.visualstudio.com/items?itemName=andreaslenzen.vbscript-language-server-client

Best regards,
Andreas

**Comment by fmeunierCC** [comment]
Hi,

Installed ! thanks

Good week end !


Cordialement,
[cid:image001.jpg@01D42720.33316960]<http://www.computacenter.fr/>
[cid:image002.jpg@01D42720.33316960]<https://twitter.com/ComputacenterFr>[cid:image003.jpg@01D42720.33316960]<https://www.facebook.com/Computacenter.en.France>[cid:image004.jpg@01D42720.33316960]<https://www.linkedin.com/company/computacenter>

Franck MEUNIER
Ingénieur
Port : (+33) 6 09 15 18 39
E-mail : franck.meunier@computacenter.fr<mailto:franck.meunier@computacenter.fr>
COMPUTACENTER
10 rue du Lt Parayre - Espace WAGNER - Bâtiment C - 1er étage - 13090  AIX-EN-PROVENCE - FRANCE
www.computacenter.fr<http://www.computacenter.fr/>


De : Andreas Lenzen [mailto:notifications@github.com]
Envoyé : dimanche 29 juillet 2018 09:15
À : Luncher91/VBScript-vscode <VBScript-vscode@noreply.github.com>
Cc : MEUNIER, Franck <Franck.MEUNIER@computacenter.com>; Author <author@noreply.github.com>
Objet : Re: [Luncher91/VBScript-vscode] how to install? (#15)


Hi,

Just start vscode, press Ctrl+P and paste "ext install andreaslenzen.vbscript-language-server-client"

That installs the extension from the MS marketplace. You can find this extension within the marketplace on the web https://marketplace.visualstudio.com/items?itemName=andreaslenzen.vbscript-language-server-client

Best regards,
Andreas

**Comment by Luncher91** [comment]
You are very welcome 🙂

**Comment by fmeunierCC** [comment]
When I try running a simple VB script I can’t see environment for VB in the environment selector… what I missed


[cid:image001.png@01D42741.35A06A90]


Cordialement,
[cid:image002.jpg@01D42741.35A06A90]<http://www.computacenter.fr/>
[cid:image003.jpg@01D42741.35A06A90]<https://twitter.com/ComputacenterFr>[cid:image004.jpg@01D42741.35A06A90]<https://www.facebook.com/Computacenter.en.France>[cid:image005.jpg@01D42741.35A06A90]<https://www.linkedin.com/company/computacenter>

Franck MEUNIER
Ingénieur
Port : (+33) 6 09 15 18 39
E-mail : franck.meunier@computacenter.fr<mailto:franck.meunier@computacenter.fr>
COMPUTACENTER
10 rue du Lt Parayre - Espace WAGNER - Bâtiment C - 1er étage - 13090  AIX-EN-PROVENCE - FRANCE
www.computacenter.fr<http://www.computacenter.fr/>


De : Andreas Lenzen [mailto:notifications@github.com]
Envoyé : dimanche 29 juillet 2018 11:06
À : Luncher91/VBScript-vscode <VBScript-vscode@noreply.github.com>
Cc : MEUNIER, Franck <Franck.MEUNIER@computacenter.com>; Author <author@noreply.github.com>
Objet : Re: [Luncher91/VBScript-vscode] how to install? (#15)


You are very welcome 🙂

**Comment by fmeunierCC** [comment]
When I try running a simple VB script I can’t see environment for VB in the environment selector… what I missed

![capture](https://user-images.githubusercontent.com/36441116/43367219-00f4e74c-934a-11e8-8945-30ad264ed9e3.JPG)

**Comment by Luncher91** [comment]
This extension does not support debugging, yet. For Syntax higblighting I recommend to install either https://marketplace.visualstudio.com/items?itemName=luggage66.VBScript or https://marketplace.visualstudio.com/items?itemName=Darfka.vbscript

But nevertheless I am working on the debug functionality. You can learn more about that in issue #3.

**Comment by fmeunierCC** [comment]
Thanks again!
________________________________
De :Andreas Lenzen <notifications@github.com>
Envoyé : dimanche 29 juillet 2018 17:02
À : Luncher91/VBScript-vscode <VBScript-vscode@noreply.github.com>
CC : "MEUNIER, Franck" <Franck.MEUNIER@computacenter.com>,Author <author@noreply.github.com>
Objet : Re: [Luncher91/VBScript-vscode] how to install? (#15)



This extension does not support debugging, yet. For Syntax higblighting I recommend to install either https://marketplace.visualstudio.com/items?itemName=luggage66.VBScript or https://marketplace.visualstudio.com/items?itemName=Darfka.vbscript

But nevertheless I am working on the debug functionality. You can learn more about that in issue #3<https://github.com/Luncher91/VBScript-vscode/issues/3>.

-

**Comment by FreZZZeR-I** [comment]
Hello!
Can you tell me about debugger development status?
Thx
